name: Update

on:
  schedule:
    - cron: '20 8,1 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout current repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Needed to properly push changes later
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
    
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r crawler/requirements.txt

      - name: Checkout target repository (crawler files only)
        uses: actions/checkout@v4
        with:
          repository: wxbtt/wz
          token: ${{ secrets.PRIVATE_REPO_TOKEN }}
          path: target-repo
          sparse-checkout: |
            crawler/config.py
            crawler/main.py

      - name: Copy required files from target repository
        run: |
          # Copy config.py and main.py from target repo's crawler folder
          if [ -f "target-repo/crawler/config.py" ]; then
            cp target-repo/crawler/config.py $GITHUB_WORKSPACE/
            echo "Copied config.py to workspace"
          else
            echo "Error: target-repo/crawler/config.py not found"
            exit 1
          fi
          
          if [ -f "target-repo/crawler/main.py" ]; then
            cp target-repo/crawler/main.py $GITHUB_WORKSPACE/
            echo "Copied main.py to workspace"
          else
            echo "Error: target-repo/crawler/main.py not found"
            exit 1
          fi

      - name: Run main.py
        run: |
          cd ${{ github.workspace }}
          python main.py
          ls -l  # Check the generated files

      - name: Update only ruanya and heimao cangku folders
        run: |
          # Configure git
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          
          # Add only the specific folders we want to update
          git add ruanya/
          git add "heimao cangku/"
          
          # Check if there are changes to commit
          if git diff-index --quiet HEAD --; then
            echo "No changes to commit"
          else
            git commit -m "Update ruanya and heimao cangku folders with latest crawl results"
            git push
          fi

      - name: Clean up
        run: |
          # Remove the copied Python files
          rm -f ${{ github.workspace }}/config.py
          rm -f ${{ github.workspace }}/main.py
          echo "Clean up completed"