name: Update

on:
  schedule:
    - cron: '20 8,1 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout current repository
        uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
    
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r crawler/requirements.txt

      - name: Create temporary crawler directory
        run: |
          mkdir -p ${{ github.workspace }}/temp_crawler
          echo "Temporary directory created"

      - name: Checkout target repository (crawler files only)
        uses: actions/checkout@v4
        with:
          repository: wxbtt/wz
          token: ${{ secrets.PRIVATE_REPO_TOKEN }}
          path: target-repo
          sparse-checkout: |
            crawler/config.py
            crawler/main.py

      - name: Copy crawler files to temporary directory
        run: |
          if [ -f "target-repo/crawler/config.py" ]; then
            cp target-repo/crawler/config.py $GITHUB_WORKSPACE/temp_crawler/
            echo "Copied config.py to temp_crawler"
          else
            echo "Error: config.py not found"
            exit 1
          fi
          
          if [ -f "target-repo/crawler/main.py" ]; then
            cp target-repo/crawler/main.py $GITHUB_WORKSPACE/temp_crawler/
            echo "Copied main.py to temp_crawler"
          else
            echo "Error: main.py not found"
            exit 1
          fi

      - name: Run crawler from temporary directory
        run: |
          cd ${{ github.workspace }}/temp_crawler
          python main.py
          # Move all generated files to root directory
          shopt -s dotglob
          mv * $GITHUB_WORKSPACE/ || echo "No files to move"
          cd $GITHUB_WORKSPACE
          ls -l  # Show files in root directory

      - name: Update repository with results
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git status
          git commit -m "Auto-update: $(date +'%Y-%m-%d %H:%M:%S')"
          git push

      - name: Clean up temporary files
        run: |
          rm -rf ${{ github.workspace }}/temp_crawler
          echo "Temporary files cleaned up"