name: Update

on:
  schedule:
    - cron: '20 8,1 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. 检出当前仓库（用于后续保存结果）
      - name: Checkout current repository
        uses: actions/checkout@v4
      
      # 2. 设置Python环境
      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
    
      # 3. 安装依赖（假设requirements.txt在当前仓库）
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f "crawler/requirements.txt" ]; then
            pip install -r crawler/requirements.txt
          else
            echo "Warning: requirements.txt not found, skipping install"
          fi

      # 4. 创建临时隔离目录（内存文件系统，运行后自动销毁）
      - name: Create ephemeral workspace
        run: |
          mkdir -p /tmp/crawler_workspace
          echo "Created temporary workspace in /tmp"

      # 5. 仅下载目标仓库的爬虫文件到临时目录
      - name: Download crawler scripts
        uses: actions/checkout@v4
        with:
          repository: wxbtt/wz
          token: ${{ secrets.PRIVATE_REPO_TOKEN }}
          path: /tmp/crawler_workspace/source
          sparse-checkout: |
            crawler/config.py
            crawler/main.py
          clean: true

      # 6. 验证并运行爬虫
      - name: Execute crawler
        run: |
          cd /tmp/crawler_workspace/source/crawler
          echo "Current directory: $(pwd)"
          ls -l
          
          # 安装临时依赖（如果需要）
          if [ -f "requirements.txt" ]; then
            pip install -r requirements.txt
          fi
          
          # 运行爬虫（结果直接生成到当前仓库根目录）
          python main.py --output-dir $GITHUB_WORKSPACE
          
          # 验证输出
          echo "Generated files in repo root:"
          ls -l $GITHUB_WORKSPACE

      # 7. 提交爬取结果到当前仓库
      - name: Commit results
        run: |
          cd $GITHUB_WORKSPACE
          git config --local user.email "actions@github.com"
          git config --local user.name "Automatic Updater"
          
          # 只添加非Python文件
          find . -type f -not -name '*.py' -not -path './.git/*' -exec git add {} +
          
          git status
          if [ -n "$(git status --porcelain)" ]; then
            git commit -m "Data update: $(date +'%Y-%m-%d %H:%M:%S')"
            git push
          else
            echo "No changes to commit"
          fi

      # 8. 彻底清理（即使之前步骤失败也会执行）
      - name: Nuclear cleanup
        if: always()
        run: |
          echo "Performing final cleanup..."
          rm -rf /tmp/crawler_workspace
          echo "Checking for leftover Python files:"
          find $GITHUB_WORKSPACE -name '*.py' -not -path './.git/*' | grep -v requirements.txt || echo "No Python files found"