name: Update

on:
  schedule:
    - cron: '0 18 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout current repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # 获取完整历史记录，便于后续git操作
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
    
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r crawler/requirements.txt

      - name: Checkout target repository (crawler files only)
        uses: actions/checkout@v4
        with:
          repository: wxbtt/wz
          token: ${{ secrets.PRIVATE_REPO_TOKEN }}
          path: target-repo
          sparse-checkout: |
            crawler/config.py
            crawler/main.py

      - name: Copy required files from target repository to root
        run: |
          # Copy config.py and main.py from target repo's crawler folder to root
          if [ -f "target-repo/crawler/config.py" ]; then
            cp target-repo/crawler/config.py $GITHUB_WORKSPACE/
            echo "Copied config.py to root directory"
          else
            echo "Error: target-repo/crawler/config.py not found"
            exit 1
          fi
          
          if [ -f "target-repo/crawler/main.py" ]; then
            cp target-repo/crawler/main.py $GITHUB_WORKSPACE/
            echo "Copied main.py to root directory"
          else
            echo "Error: target-repo/crawler/main.py not found"
            exit 1
          fi

      - name: Run main.py
        run: |
          cd ${{ github.workspace }}
          python main.py
          ls -l  # Check the generated files

      - name: Clean up temporary files and directories
        run: |
          # Remove Python temporary files
          rm -f ${{ github.workspace }}/config.py
          rm -f ${{ github.workspace }}/main.py
          
          # Remove Python cache directories
          find ${{ github.workspace }} -name "__pycache__" -type d -exec rm -rf {} + || true
          
          # Remove target-repo directory
          rm -rf ${{ github.workspace }}/target-repo
          
          # Remove crawl.log if exists
          rm -f ${{ github.workspace }}/crawl.log
          
          echo "Clean up completed - removed all temporary files and directories"

      - name: Check for changes before commit
        id: check-changes
        run: |
          # 检查是否有文件被修改或新增
          git add .
          if git diff-index --quiet HEAD --; then
            echo "No changes detected"
            echo "has_changes=false" >> $GITHUB_OUTPUT
          else
            echo "Changes detected"
            echo "has_changes=true" >> $GITHUB_OUTPUT
          fi

      - name: Commit and push changes
        if: steps.check-changes.outputs.has_changes == 'true'
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git commit -m "Update with latest crawl results [automated]"
          git push