name: Update

on:
  schedule:
    - cron: '20 8,1 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout current repository
        uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
    
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r crawler/requirements.txt

      - name: Checkout target repository (crawler files only)
        uses: actions/checkout@v4
        with:
          repository: wxbtt/wz
          token: ${{ secrets.PRIVATE_REPO_TOKEN }}
          path: target-repo
          sparse-checkout: |
            crawler/config.py
            crawler/main.py

      - name: Copy required files from target repository to root
        run: |
          # Copy config.py and main.py from target repo's crawler folder to root
          if [ -f "target-repo/crawler/config.py" ]; then
            cp target-repo/crawler/config.py $GITHUB_WORKSPACE/
            echo "Copied config.py to root directory"
          else
            echo "Error: target-repo/crawler/config.py not found"
            exit 1
          fi
          
          if [ -f "target-repo/crawler/main.py" ]; then
            cp target-repo/crawler/main.py $GITHUB_WORKSPACE/
            echo "Copied main.py to root directory"
          else
            echo "Error: target-repo/crawler/main.py not found"
            exit 1
          fi

      - name: Run main.py
        run: |
          cd ${{ github.workspace }}
          python main.py
          ls -l  # Check the generated files

      - name: Clean up Python files
        run: |
          # Remove the copied Python files from root directory
          rm -f ${{ github.workspace }}/config.py
          rm -f ${{ github_workspace }}/main.py
          echo "Clean up completed - removed config.py and main.py"

      - name: Update current repository with results
        run: |
          # Add any files generated by main.py to current repository
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit -m "Update with latest crawl results"
          git push
